### ISSUE TITLE
Bastions do not prevent reinforcements

### ISSUE THREAD

**Issue by Falvyu** [CivClassic/Bastion#12]
Hostile bastions (City and Vault) don't block reinforcements.

~I have not been able to reproduce this bug on my test server.~

Nevermind, I was still on my local civ14 branch (`71ce8fc723f54e0e437bdb4ac408c9e468abac7a`) and the bug wasn't present. The bug is present on the latest version on `master`.

EDIT: Seems to have been broken by `e554b4b457d7b2bfea182b77e2c04fbc4ebbf6f5`

**Comment by Maxopoly** [comment]
Should be fixed by https://github.com/CivClassic/Bastion/commit/cb9858493d5342b8569e977bdecffdde6335d18b
