### ISSUE TITLE
Playersetting/GUI Overlay for /bsi

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/Bastion#7]
Can copy almost everything from /cti

https://github.com/CivClassic/Citadel/blob/master/src/main/java/vg/civcraft/mc/citadel/listener/ModeListener.java

**Comment by Diet-Cola** [comment]
Would there be a performant way to do this in such a way that while /bsi is active, the overlay would provide a real time "Friendly Bastion Field", "Enemy Bastion Field" or "No Bastion Field"?

**Comment by Maxopoly** [comment]
Yes, you could just update it once a second for all players, that'd be fine.

**Comment by Maxopoly** [comment]
https://github.com/CivClassic/Bastion/pull/10
